// AUTO-GENERATED by scripts/gen-server-packages.ts — do not edit by hand.
export const SERVER_EXTERNAL_PACKAGES = [
  "@kubernetes/client-node",
  "avsc",
  "dockerode",
  "ioredis",
  "kafkajs",
  "mongodb",
  "mssql",
  "mysql2",
  "pg",
  "ssh2",
  "tedious"
] as const;
