import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { TECH_META_LIST } from "@/techs/meta-registry";

const pkgs = [...new Set(TECH_META_LIST.flatMap((m) => m.serverPackages ?? []))].sort();
const body =
  `// AUTO-GENERATED by scripts/gen-server-packages.ts — do not edit by hand.\n` +
  `export const SERVER_EXTERNAL_PACKAGES = ${JSON.stringify(pkgs, null, 2)} as const;\n`;
writeFileSync(resolve(process.cwd(), "src/techs/server-packages.generated.ts"), body);
console.log(`Wrote ${pkgs.length} server external packages.`);
